version: "3.8"

volumes:
    lidardata:

services:
  api:
    image: pytree:0.0.1
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-DEV}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: /app/start_server.sh
    volumes:
      - ".:/app" #DEV ONLY!!!
    ports:
      - "6001:5000"
