vars:
    debug: false
    server_url: your_server_url
    gmf_url: ""
    cpotree_executable: path_to_cpotre.exe
    # Available point clouds
    pointclouds:
        my_cloud: path_to_potree_cloud

    # Classification colors
    classification_colors:
        0:
            color: 100, 250, 100
            name: manque de classe
            visible: 1
        1:
            color: 100, 100, 100
            name: pas de classe
            visible: 1
        2:
            color: 200, 200, 200
            name: sol
            visible: 1
        3:
            color: 0, 125, 0
            name: toto
            visible: 1
        4:
            color: 0, 250, 125
            name: titi
            visible: 1
        5:
            color: 40, 150, 0
            name: vegetation
            visible: 1
        6:
            color: 140, 50, 0
            name: batiment
            visible: 1
        8:
            color: 250, 250, 0
            name: batiment
            visible: 1
        7:
            color: 120, 120, 120
            name: waaw
            visible: 1
        10:
            color: 0, 89, 98
            name: 10
            visible: 1
        13:
            color: 120, 120, 120
            name: tutu
            visible: 1
        14:
            color: 120, 120, 120
            name: wewe
            visible: 1
        23:
            color: 120, 120, 250
            name: mal connu
            visible: 1
        31:
            color: 0, 120, 120
            name: bibi
            visible: 1

    # Default profile material
    default_material: COLOR_PACKED

    #NOT IMPLEMENTED: required ?
    published_attributes: [INTENSITY,COLOR_PACKED,CLASSIFICATION]

    #****************************
    # GMF 1 support
    #****************************
    
    max_levels:
      100: 
        max: 11
      250: 
        max: 10
      500: 
        max: 9
      1000:
        max: 8
      100000:
        max: 7

    # Class that you might have forgotten to define...
    undefined_class: Classe inconnue
    
    # LIDAR classes configuration
    classes_names_standard:
      1: never_classified
      2: Ground
      3: Low_Vegetation_2010
      4: High_Vegetation_2010
      5: Building_2010
      6: Building
      7: Low_Point
      8: Model_Key_point
      9: Water_2010
      10: ASPRS_Reserved
      11: ASPRS_Reserved
      12: Overlap
      13: Wire - Guard (Shield)
      14: Wire - Conductor (Phase)
      15: Transmission Towers
      16: Wire-structure Connector
      17: Bridge Deck
      18: High Noise
      64: Voitures
      65: Grues et temporaire
      70: Facades
      71: Murs
      99: Hors périmetre

    minLOD: 0
    maxLOD: 8
    width: 3
    default_point_cloud: my_default_cloud
